TEMPLATE_NAME = "template.png"
OUTPUT_NAME = "results.png"

RED = "#ef3f85"
BLUE = "#3a83c4"
WHITE = "#ffffff"
GREY = "#8b8b9f"

READABLE_DATE = "%d de %b del %Y a las %H:%M:%S"

PRIMARY_FONT = "LEMONMILK-Regular.otf"
SECONDARY_FONT = "Nunito-Regular.ttf"

UPDATE_TIME_FONT_SIZE = 14
MAIN_PERC_FONT_SIZE = 50
MAIN_VOTES_FONT_SIZE = 20
DETAIL_FONT_SIZE = 10

TOTAL_VOTANTES = 14796197
TOTAL_MESAS = 44916

UPDATE_TIME_Y = 0

FIRST_PERC_Y = 1
FIRST_TOTAL_VOTES_Y = 2
FIRST_DOUGHNUT_Y = 2

FIRST_DETAIL1_Y = 2
FIRST_DETAIL2_Y = 2


SECOND_PERC_Y = 3
SECOND_TOTAL_VOTES_Y = 4
SECOND_DOUGHNUT_Y = 2

SECOND_DETAIL1_Y = 2
SECOND_DETAIL2_Y = 2

UPDATE_TIME_X = 0

LEFT_PERC_X = 0
DOUGHNUT_X = 0
RIGHT_PERC_X = 0

BOXES_DETAIL_X = 0
VOTES_DETAIL_X = 0
INVALID_DETAIL_X = 0